apiVersion: v1
kind: Secret
metadata:
  name: account-postgres-secret
  namespace: finance-tracker
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: financedb-accounts