apiVersion: v1
kind: Secret
metadata:
  name: account-postgres-secret
  namespace: financetracker
type: Opaque
data:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: financedb-accounts