apiVersion: v1
kind: Secret
metadata:
  name: budget-postgres-secret
  namespace: financetracker
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: financedb-budgets
