apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: financetracker
type: Opaque
data:
  # echo -n 'StandardSecretKeyForACLProject2026_32Bytes' | base64
  jwt-secret: U3RhbmRhcmRTZWNyZXRLZXlGb3JBQ0xQcm9qZWN0MjAyNl8zMkJ5dGVz
