apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: financetracker
type: Opaque
data:
  JWT_SECRET: U3RhbmRhcmRTZWNyZXRLZXlGb3JBQ0xQcm9qZWN0MjAyNl8zMkJ5dGVz
  jwt-secret: U3RhbmRhcmRTZWNyZXRLZXlGb3JBQ0xQcm9qZWN0MjAyNl8zMkJ5dGVz
