apiVersion: v1
kind: Secret
metadata:
  name: transaction-postgres-secret
  namespace: financetracker
type: Opaque
stringData:
  POSTGRES_USER: user
  POSTGRES_PASSWORD: userpass
  POSTGRES_DB: financedb-transactions
