server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: api-gateway
  main:
    allow-bean-definition-overriding: ${SPRING_MAIN_ALLOW_BEAN_DEFINITION_OVERRIDING:false}
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: ${USER_SERVICE_URL:http://user-service:8080}
          predicates:
            - Path=/api/users/**, /api/auth/**
        - id: account-service
          uri: ${ACCOUNT_SERVICE_URL:http://account-service:8080}
          predicates:
            - Path=/api/accounts/**
        - id: transaction-service
          uri: ${TRANSACTION_SERVICE_URL:http://transaction-service:8080}
          predicates:
            - Path=/api/transactions/**
        - id: budget-service
          uri: ${BUDGET_SERVICE_URL:http://budget-service:8080}
          predicates:
            - Path=/api/budgets/**
        - id: reporting-service
          uri: ${REPORTING_SERVICE_URL:http://reporting-service:8080}
          predicates:
            - Path=/api/reports/**

management:
  endpoints:
    web:
      exposure:
        include: "prometheus,health,info"
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true

