apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: finance-tracker
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      # S2-INFRA scrape job
      - job_name: account-service
        metrics_path: /actuator/prometheus
        static_configs:
          - targets: ["account-service.finance-tracker.svc.cluster.local:8080"]

      # S5-INFRA scrape job
      - job_name: reporting-service
        metrics_path: /actuator/prometheus
        static_configs:
          - targets: ["reporting-service.finance-tracker.svc.cluster.local:8080"]
      # S4-INFRA scrape job
      - job_name: budget-service
        metrics_path: /actuator/prometheus
        static_configs:
          - targets: ["budget-service.finance-tracker.svc.cluster.local:8080"]
      # S3-INFRA scrape job
      - job_name: transaction-service
        static_configs:
          - targets: ["transaction-service.finance-tracker.svc.cluster.local:8080"]
        metrics_path: /actuator/prometheus