server:
  port: 8080

spring:
  application:
    name: reporting-service

  datasource:
    url: jdbc:postgresql://localhost:5432/financedb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      password: ${SPRING_DATA_REDIS_PASSWORD:redispass}

    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://root:rootpass@localhost:27017/financemongo?authSource=admin}

jwt:
  secret: "ThisIsAFallbackSecretKeyThatIsAtLeast32BytesLongForLocalDev"
  expiration: 86400000 # 24 hours in ms
