apiVersion: v1
kind: ConfigMap
metadata:
  name: account-service-configmap
  namespace: financetracker
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://account-postgres:5432/financedb-accounts
  SPRING_DATASOURCE_USERNAME: user
  SPRING_RABBITMQ_HOST: rabbitmq
  FEIGN_USER_SERVICE_URL: http://user-service:8080
  FEIGN_TRANSACTION_SERVICE_URL: http://transaction-service:8080