apiVersion: v1
kind: ConfigMap
metadata:
  name: account-service-configmap
  namespace: financetracker
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://account-postgres:5432/financedb-accounts
  SPRING_DATASOURCE_USERNAME: user
  SPRING_RABBITMQ_HOST: rabbitmq
  SPRING_DATA_REDIS_HOST: redis
  SPRING_ELASTICSEARCH_URIS: http://elasticsearch:9200
  FEIGN_ACCOUNT_SERVICE_URL: http://account-service:8080
  FEIGN_USER_SERVICE_URL: http://user-service:8080
  FEIGN_TRANSACTION_SERVICE_URL: http://transaction-service:8080
  FEIGN_BUDGET_SERVICE_URL: http://budget-service:8080
  FEIGN_REPORTING_SERVICE_URL: http://reporting-service:8080