apiVersion: v1
kind: ConfigMap
metadata:
  name: reporting-service-configmap
  namespace: financetracker
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://reporting-postgres:5432/financedb-reporting"
  SPRING_RABBITMQ_HOST: "rabbitmq"
  FEIGN_USER_SERVICE_URL: "http://user-service:8080"
  FEIGN_ACCOUNT_SERVICE_URL: "http://account-service:8080"
  FEIGN_TRANSACTION_SERVICE_URL: "http://transaction-service:8080"
  FEIGN_BUDGET_SERVICE_URL: "http://budget-service:8080"
