apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cassandra-pvc
  namespace: financetracker
  labels:
    app: cassandra
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
