DROP TABLE IF EXISTS transaction_splits;
DROP TABLE IF EXISTS transactions;
DROP TABLE IF EXISTS accounts;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255),
    name VARCHAR(255),
    "role" VARCHAR(50) NOT NULL,
    preferences VARCHAR(4096)
);

CREATE TABLE accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    balance DOUBLE PRECISION NOT NULL
);

CREATE TABLE transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL,
    to_account_id BIGINT,
    user_id BIGINT NOT NULL,
    approver_id BIGINT,
    type VARCHAR(50) NOT NULL,
    amount DOUBLE PRECISION NOT NULL,
    currency VARCHAR(10) NOT NULL,
    category VARCHAR(50) NOT NULL,
    description VARCHAR(1024),
    status VARCHAR(50) NOT NULL,
    metadata VARCHAR(4096),
    transaction_date TIMESTAMP NOT NULL,
    completed_at TIMESTAMP
);

CREATE TABLE transaction_splits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id BIGINT NOT NULL,
    split_order INTEGER NOT NULL,
    recipient_name VARCHAR(255) NOT NULL,
    amount DOUBLE PRECISION NOT NULL,
    description VARCHAR(255) NOT NULL,
    status VARCHAR(50) NOT NULL,
    metadata VARCHAR(4096),
    CONSTRAINT fk_transaction FOREIGN KEY (transaction_id) REFERENCES transactions(id)
);
