CREATE TABLE IF NOT EXISTS users (
    id BIGINT PRIMARY KEY,
    "role" VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS accounts (
    id BIGINT PRIMARY KEY,
    balance DOUBLE PRECISION NOT NULL
);
