apiVersion: apps/v1
kind: Deployment
metadata:
  name: budget-service
  namespace: financetracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: budget-service
  template:
    metadata:
      labels:
        app: budget-service
    spec:
      containers:
        - name: budget-service
          image: budget-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: budget-service-configmap
            - secretRef:
                name: budget-postgres-secret
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: jwt-secret
            - name: JAVA_TOOL_OPTIONS
              value: "-XX:MaxRAMPercentage=50.0 -XX:InitialRAMPercentage=25.0"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          startupProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 15
            failureThreshold: 80
          readinessProbe:
            tcpSocket:
              port: 8080
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            tcpSocket:
              port: 8080
            periodSeconds: 20
            failureThreshold: 3
