rabbitmq.exchanges.account=account.events
rabbitmq.exchanges.transaction=transaction.events
rabbitmq.queues.transaction-approved-listener=account.transaction.approved-listener
rabbitmq.queues.transaction-approved-listener-dlq=account.transaction.approved-listener.dlq
rabbitmq.queues.transaction-completed-listener=account.transaction.completed-listener
rabbitmq.queues.transaction-completed-listener-dlq=account.transaction.completed-listener.dlq
rabbitmq.queues.transaction-voided-listener=account.transaction.voided-listener
rabbitmq.queues.transaction-voided-listener-dlq=account.transaction.voided-listener.dlq
rabbitmq.routing-keys.transaction-approved=transaction.approved
rabbitmq.routing-keys.transaction-completed=transaction.completed
rabbitmq.routing-keys.transaction-voided=transaction.voided
