rabbitmq.exchanges.account=account.events
rabbitmq.exchanges.transaction=transaction.events
rabbitmq.queues.transaction-saga-listener=account.transaction.saga-listener
rabbitmq.queues.transaction-saga-listener-dlq=account.transaction.saga-listener.dlq
rabbitmq.routing-keys.transaction-approved=transaction.approved
rabbitmq.routing-keys.transaction-completed=transaction.completed
rabbitmq.routing-keys.transaction-voided=transaction.voided
