server:
  port: 8080

spring:
  application:
    name: budget-service
  datasource:
    url: jdbc:postgresql://budget-postgres:5432/financedb-budgets
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379
      password: redispass
#    cassandra:
#      contact-points: ${CASSANDRA_HOST:localhost}
#      port: 9042
#      local-datacenter: ${CASSANDRA_DC:datacenter1}
#      keyspace-name: financeks
#      schema-action: CREATE_IF_NOT_EXISTS
  mongodb:
    uri: mongodb://root:rootpass@${MONGO_HOST:localhost}:27017/financemongo?authSource=admin&serverSelectionTimeoutMS=50&connectTimeoutMS=50&socketTimeoutMS=50
  cassandra:
    contact-points: ${CASSANDRA_HOST:localhost}
    port: 9042
    local-datacenter: ${CASSANDRA_DC:datacenter1}
    keyspace-name: financeks
    schema-action: CREATE_IF_NOT_EXISTS
    connection:
      connect-timeout: 15s
      init-query-timeout: 15s
    request:
      timeout: 15s

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        acknowledge-mode: auto
        default-requeue-rejected: false
        retry:
          enabled: true
          initial-interval: 1000
          # max-attempts is deprecated, max-retries should be used instead
          max-retries: 3

jwt:
  secret: ${JWT_SECRET:ThisIsAFallbackSecretKeyThatIsAtLeast32BytesLongForLocalDev}
  expiration: 86400000 # 24 hours in ms

logging:
  level:
    org.springframework.cache: TRACE
    org.springframework.data.redis: TRACE

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: budget-service

feign:
  user-service:
    url: http://user-service:8080