apiVersion: v1
kind: Service
metadata:
  name: budget-postgres
  namespace: financetracker
spec:
  clusterIP: None
  selector:
    app: budget-postgres
  ports:
    - port: 5432
      targetPort: 5432
