apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: neo4j
  namespace: financetracker
spec:
  serviceName: "neo4j"
  replicas: 1
  selector:
    matchLabels:
      app: neo4j
  template:
    metadata:
      labels:
        app: neo4j
    spec:
      enableServiceLinks: false
      containers:
        - name: neo4j
          image: neo4j:5.18.0
          env:
            - name: NEO4J_AUTH
              value: "neo4j/neo4jpass"
            - name: NEO4J_server_memory_heap_max__size
              value: "256m"
            - name: NEO4J_server_memory_heap_initial__size
              value: "128m"
            - name: NEO4J_server_memory_pagecache_size
              value: "64m"
          ports:
            - containerPort: 7687
              name: bolt
            - containerPort: 7474
              name: http
          resources:
            requests:
              memory: "256Mi"
              cpu: "150m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /
              port: 7474
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 6
          volumeMounts:
            - name: neo4j-data
              mountPath: /data
      volumes:
        - name: neo4j-data
          persistentVolumeClaim:
            claimName: neo4j-pvc
