apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: transaction-postgres
  namespace: financetracker
spec:
  serviceName: transaction-postgres
  replicas: 1
  selector:
    matchLabels:
      app: transaction-postgres
  template:
    metadata:
      labels:
        app: transaction-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:17
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: transaction-postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: transaction-postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: transaction-postgres-secret
                  key: POSTGRES_DB
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: transaction-postgres-pvc
